const slots = [
  ['head','머리','할리퀸 관모','Harlequin Crest','모든 기술 +2','생명력 +134'],['amulet','목걸이','마라의 만화경','Mara’s Kaleidoscope','모든 기술 +2','모든 저항 +30'],['weapon','주 무기','참나무의 심장','Heart of the Oak','패캐 +40%','모든 기술 +3'],['offhand','보조 장비','영혼','Spirit Monarch','패캐 +35%','마나 +112'],['armor','갑옷','수수께끼','Enigma','모든 기술 +2','힘 +67'],['gloves','장갑','트래그울의 발톱','Trang-Oul’s Claws','패캐 +20%','독 기술 +2'],['ring1','왼쪽 반지','요르단의 반지','Stone of Jordan','모든 기술 +1','마나 +25%'],['ring2','오른쪽 반지','칠흑 서리','Raven Frost','빙결되지 않음','민첩 +20'],['belt','허리띠','거미 그물띠','Arachnid Mesh','패캐 +20%','모든 기술 +1'],['boots','장화','모래폭풍 여로','Sandstorm Trek','패힛 +20%','활력 +15']
].map(([id,label,name,en,mod1,mod2])=>({id,label,name,en,mods:[mod1,mod2]}))
const catalog=[['Harlequin Crest','Shako','고유 · LV 62','모든 기술 +2','생명력 +134'],['Heart of the Oak','Flail','룬워드 · LV 55','패캐 +40%','모든 저항 +40'],['Spirit','Monarch','룬워드 · LV 54','패캐 +35%','마나 +112'],['Enigma','Mage Plate','룬워드 · LV 65','순간이동 +1','모든 기술 +2'],['Arachnid Mesh','Spiderweb Sash','고유 · LV 80','패캐 +20%','모든 기술 +1'],['Trang-Oul’s Claws','Heavy Bracers','세트 · LV 45','패캐 +20%','독 기술 +2']]
const state={concept:new URLSearchParams(location.search).get('concept')||'armory',selected:'weapon',query:''}
const concepts={armory:{badge:'A',title:'무기고',summary:'착용 슬롯을 큰 카드와 인체형 배치로 확인하고, 선택한 장비의 옵션을 옆에서 읽는 안입니다.',detail:'추천안 · 착용 현황과 상세 정보 균형'},ledger:{badge:'B',title:'장비 원장',summary:'모든 부위를 한 줄씩 크게 펼쳐 아이템 이름과 핵심 옵션을 빠르게 훑는 안입니다.',detail:'목록 가독성 우선 · 키보드/모바일 친화적'},workbench:{badge:'C',title:'아이템 워크벤치',summary:'검색 결과, 아이템 상세, 현재 착용 장비를 세 영역으로 나눠 탐색과 비교를 강화한 안입니다.',detail:'검색·비교 우선 · 데이터베이스 활용 최적화'}}
const selected=()=>slots.find(x=>x.id===state.selected)||slots[0]
const slotCard=s=>`<button class="slot-card ${s.id===state.selected?'selected':''}" data-slot="${s.id}"><i>${s.id==='weapon'?'†':s.id==='offhand'?'◈':'◇'}</i><span><small>${s.label}</small><strong>${s.name}</strong><em>${s.en}</em></span><b>${s.mods[0]}</b></button>`
const detail=s=>`<aside class="item-detail panel"><small>SELECTED SLOT · ${s.label}</small><h2>${s.name}</h2><p>${s.en}</p><div class="item-art">${s.id==='weapon'?'†':'◇'}</div><h3>적용 옵션</h3>${s.mods.map(m=>`<div class="mod">${m}<strong>✓</strong></div>`).join('')}<div class="detail-actions"><button>비교 후보</button><button class="primary">아이템 변경</button></div></aside>`
function armory(){const s=selected();return `<div class="armory-layout"><section class="loadout panel"><header><div><small>ACTIVE LOADOUT</small><h2>착용 장비</h2></div><span>10 / 10 슬롯</span></header><div class="paperdoll">${slots.map(slotCard).join('')}<div class="silhouette">☠</div></div></section>${detail(s)}</div>`}
function ledger(){return `<section class="gear-ledger panel"><header><div><small>GEAR LEDGER</small><h2>전체 장비</h2></div><div class="summary-chips"><span>모든 기술 +13</span><span>패캐 125%</span><span>저항 +70</span></div></header>${slots.map(s=>`<article class="gear-row ${s.id===state.selected?'selected':''}" data-slot="${s.id}"><div class="slot-label"><i>◇</i><span><small>${s.id.toUpperCase()}</small><strong>${s.label}</strong></span></div><div class="gear-name"><strong>${s.name}</strong><span>${s.en}</span></div><div class="row-mods">${s.mods.map(m=>`<span>${m}</span>`).join('')}</div><button>변경</button></article>`).join('')}</section>`}
function workbench(){const filtered=catalog.filter(i=>i.join(' ').toLowerCase().includes(state.query.toLowerCase()));const s=selected();return `<div class="workbench"><section class="catalog panel"><header><small>3.3 ITEM CATALOG</small><h2>아이템 찾기</h2></header><input id="search" aria-label="아이템 검색" placeholder="이름 또는 옵션 검색" value="${state.query}"><div class="filters"><button class="active">전체</button><button>고유</button><button>세트</button><button>룬워드</button></div><div class="results">${filtered.map((i,n)=>`<button class="result ${n===0?'selected':''}" data-catalog="${n}"><small>${i[2]}</small><strong>${i[0]}</strong><span>${i[1]}</span><em>${i[3]} · ${i[4]}</em></button>`).join('')||'<p class="empty">검색 결과가 없습니다.</p>'}</div></section><section class="preview panel"><small>ITEM PREVIEW</small><div class="preview-art">†</div><h2>${filtered[0]?.[0]||'아이템 선택'}</h2><p>${filtered[0]?.[1]||'검색 결과에서 선택하세요'}</p><div class="impact"><span>현재 장비 교체 시</span><strong>패캐 +0 · 생명력 +134</strong></div><div class="preview-mods"><span>${filtered[0]?.[3]||'—'}</span><span>${filtered[0]?.[4]||'—'}</span></div><button class="primary">${s.label}에 착용</button></section><aside class="loadout-rail panel"><small>CURRENT LOADOUT</small><h2>착용 부위</h2>${slots.slice(0,8).map(s=>`<button data-slot="${s.id}" class="${s.id===state.selected?'active':''}"><span>${s.label}</span><strong>${s.name}</strong></button>`).join('')}</aside></div>`}
function bind(){document.querySelectorAll('[data-concept]').forEach(b=>b.onclick=()=>{state.concept=b.dataset.concept;history.replaceState(null,'',`?concept=${state.concept}`);render()});document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.slot;render()});const search=document.getElementById('search');if(search)search.oninput=e=>{state.query=e.target.value;render();document.getElementById('search')?.focus()}}
function render(){if(!concepts[state.concept])state.concept='armory';const c=concepts[state.concept];document.querySelectorAll('[data-concept]').forEach(b=>b.classList.toggle('active',b.dataset.concept===state.concept));document.getElementById('concept-summary').textContent=c.summary;document.getElementById('concept-note').innerHTML=`<b>${c.badge}</b><div><strong>${c.title}</strong><p>${c.summary}</p></div><em>${c.detail}</em>`;document.getElementById('root').innerHTML=state.concept==='armory'?armory():state.concept==='ledger'?ledger():workbench();bind()}
render()
