const slots = [
  ['head','머리','할리퀸 관모','Harlequin Crest','모든 기술 +2','생명력 +134','♜'],['amulet','목걸이','마라의 만화경','Mara’s Kaleidoscope','모든 기술 +2','모든 저항 +30','◉'],['weapon','주 무기','참나무의 심장','Heart of the Oak','패캐 +40%','모든 기술 +3','†'],['offhand','보조 장비','영혼','Spirit Monarch','패캐 +35%','마나 +112','⬙'],['armor','갑옷','수수께끼','Enigma','모든 기술 +2','힘 +67','♟'],['gloves','장갑','트래그울의 발톱','Trang-Oul’s Claws','패캐 +20%','독 기술 +2','⌁'],['ring1','왼쪽 반지','요르단의 반지','Stone of Jordan','모든 기술 +1','마나 +25%','○'],['ring2','오른쪽 반지','칠흑 서리','Raven Frost','빙결되지 않음','민첩 +20','○'],['belt','허리띠','거미 그물띠','Arachnid Mesh','패캐 +20%','모든 기술 +1','═'],['boots','장화','모래폭풍 여로','Sandstorm Trek','패힛 +20%','활력 +15','♞']
].map(([id,label,name,en,mod1,mod2,glyph])=>({id,label,name,en,mods:[mod1,mod2],glyph}))
const catalog=[['Harlequin Crest','Shako','고유 · LV 62','모든 기술 +2','생명력 +134'],['Heart of the Oak','Flail','룬워드 · LV 55','패캐 +40%','모든 저항 +40'],['Spirit','Monarch','룬워드 · LV 54','패캐 +35%','마나 +112'],['Enigma','Mage Plate','룬워드 · LV 65','순간이동 +1','모든 기술 +2'],['Arachnid Mesh','Spiderweb Sash','고유 · LV 80','패캐 +20%','모든 기술 +1'],['Trang-Oul’s Claws','Heavy Bracers','세트 · LV 45','패캐 +20%','독 기술 +2']]
const state={concept:new URLSearchParams(location.search).get('concept')||'armory',selected:'weapon',query:'',weaponSet:1}
const concepts={armory:{badge:'A',title:'클래식 페이퍼돌',summary:'게임 인벤토리와 같은 신체 위치에 장비 슬롯을 놓고 선택 아이템의 옵션을 옆에서 크게 읽는 안입니다.',detail:'추천안 · 원작 위치 매칭 + 상세 정보'},ledger:{badge:'B',title:'인벤토리 보드',summary:'페이퍼돌과 10×4 소지품 격자를 한 화면에 결합해 착용과 보관의 관계를 그대로 보여주는 안입니다.',detail:'원작 화면 구조 우선 · 장비와 소지품 동시 보기'},workbench:{badge:'C',title:'교체 워크벤치',summary:'페이퍼돌의 실제 위치를 유지하면서 선택 슬롯의 검색 후보와 교체 효과를 바로 비교하는 안입니다.',detail:'위치 기억 + 아이템 검색·교체 최적화'}}
const selected=()=>slots.find(x=>x.id===state.selected)||slots[0]
const slotMarkup=s=>`<button class="equip-slot slot-${s.id} ${s.id===state.selected?'selected':''}" data-slot="${s.id}" aria-label="${s.label} ${s.name}"><small>${s.label}</small><i>${s.glyph}</i><strong>${s.name}</strong><em>${s.mods[0]}</em></button>`
const doll=(extra='')=>`<div class="doll-frame"><div class="weapon-switch"><span>무기 세트</span><button data-set="1" class="${state.weaponSet===1?'active':''}">I</button><button data-set="2" class="${state.weaponSet===2?'active':''}">II</button></div><div class="character-ghost"><span>☠</span><small>NECROMANCER</small></div><div class="paperdoll-grid">${slots.map(slotMarkup).join('')}</div>${extra}</div>`
const detail=s=>`<aside class="item-detail panel"><small>SELECTED SLOT · ${s.label}</small><h2>${s.name}</h2><p>${s.en}</p><div class="item-art">${s.glyph}</div><h3>적용 옵션</h3>${s.mods.map(m=>`<div class="mod">${m}<strong>✓</strong></div>`).join('')}<div class="detail-actions"><button>비교 후보</button><button class="primary">아이템 변경</button></div></aside>`
function armory(){return `<div class="classic-layout"><section class="classic-panel panel"><header><div><small>CLASSIC EQUIPMENT</small><h2>착용 장비</h2></div><span>게임 인벤토리 위치와 동일</span></header>${doll()}</section>${detail(selected())}</div>`}
const inventoryCells=()=>Array.from({length:40},(_,i)=>`<span class="inventory-cell ${[1,2,11,14,25,26,27,36].includes(i)?'filled':''}">${[1,2].includes(i)?'◈':[11,25].includes(i)?'◆':[14,26,27].includes(i)?'▮':''}</span>`).join('')
function ledger(){return `<div class="inventory-board panel"><header><div><small>INVENTORY BOARD</small><h2>장비와 소지품</h2></div><div class="gold-count">GOLD <strong>625,691</strong></div></header><div class="inventory-split"><section><h3>착용 장비</h3>${doll('<div class="life-orb">178<small>생명력</small></div><div class="mana-orb">203<small>마나</small></div>')}</section><section class="bag"><div class="bag-heading"><h3>소지품</h3><span>10 × 4</span></div><div class="inventory-grid">${inventoryCells()}</div><div class="bag-summary"><span>빈 공간 <strong>28칸</strong></span><span>부적 효과 <strong>저항 +15</strong></span></div></section></div></div>`}
function workbench(){const filtered=catalog.filter(i=>i.join(' ').toLowerCase().includes(state.query.toLowerCase()));const s=selected();return `<div class="swap-layout"><section class="mini-doll panel"><header><small>EQUIPMENT POSITION</small><h2>교체할 부위</h2></header>${doll()}</section><section class="catalog panel"><header><small>3.3 ITEM CATALOG · ${s.label}</small><h2>${s.name} 교체</h2></header><input id="search" aria-label="아이템 검색" placeholder="이름 또는 옵션 검색" value="${state.query}"><div class="filters"><button class="active">전체</button><button>고유</button><button>세트</button><button>룬워드</button></div><div class="results">${filtered.map((i,n)=>`<button class="result ${n===0?'selected':''}"><small>${i[2]}</small><strong>${i[0]}</strong><span>${i[1]}</span><em>${i[3]} · ${i[4]}</em></button>`).join('')||'<p class="empty">검색 결과가 없습니다.</p>'}</div></section><aside class="swap-preview panel"><small>SWAP IMPACT</small><h2>${filtered[0]?.[0]||'후보 없음'}</h2><p>${filtered[0]?.[1]||'검색 조건을 바꿔보세요'}</p><div class="compare-item"><span>현재</span><strong>${s.name}</strong>${s.mods.map(m=>`<em>${m}</em>`).join('')}</div><div class="swap-arrow">↓</div><div class="compare-item candidate"><span>교체 후</span><strong>${filtered[0]?.[0]||'—'}</strong><em>${filtered[0]?.[3]||'—'}</em><em>${filtered[0]?.[4]||'—'}</em></div><div class="impact"><span>빌드 변화</span><strong>패캐 +0 · 생명력 +134</strong></div><button class="primary">${s.label} 슬롯에 적용</button></aside></div>`}
function bind(){document.querySelectorAll('[data-concept]').forEach(b=>b.onclick=()=>{state.concept=b.dataset.concept;history.replaceState(null,'',`?concept=${state.concept}`);render()});document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.slot;render()});document.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>{state.weaponSet=Number(b.dataset.set);render()});const search=document.getElementById('search');if(search)search.oninput=e=>{state.query=e.target.value;render();document.getElementById('search')?.focus()}}
function render(){if(!concepts[state.concept])state.concept='armory';const c=concepts[state.concept];document.querySelectorAll('[data-concept]').forEach(b=>b.classList.toggle('active',b.dataset.concept===state.concept));document.getElementById('concept-summary').textContent=c.summary;document.getElementById('concept-note').innerHTML=`<b>${c.badge}</b><div><strong>${c.title}</strong><p>${c.summary}</p></div><em>${c.detail}</em>`;document.getElementById('root').innerHTML=state.concept==='armory'?armory():state.concept==='ledger'?ledger():workbench();bind()}
render()
